version: 2.1
jobs:
    Build:
        docker:
            - image: circleci/python:3.7

        working_directory: ~/repo

        steps:
            - checkout
            - run:
                name: Install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
    Test:
        docker:
            - image: circleci/python:3.7

        working_directory: ~/repo

        steps:
            - checkout
            - run:
                name: Run tests
                command: |
                    . venv/bin/activate
                    mkdir test_results
                    flake8 --exclude=venv* --statistics
                    pytest -v --junitxml=test_results/junit.xml --cov=app/app.py
            - store_test_results:
                path: test_results
            - store_artifacts:
                path: test_results

workflows:
    version: 2.1
    dependencies:
        jobs:
            - Build
            - Test:
                requires:
                    - Build
