version: 2.1

executors:
    default_env:
        docker:
            - image: circleci/python:3.7
        working_directory: ~/repo


jobs:
    build:
        executor: default_env
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - run:
                name: Install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
            - save_cache:
                      key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                      paths:
                        - "venv"

    test:
        executor: default_env
        steps:
            - checkout
            - run:
                name: Run tests
                command: |
                    . venv/bin/activate
                    mkdir test_results
                    flake8 --exclude=venv* --statistics
                    pytest -v --junitxml=test_results/junit.xml --cov=app/app.py
            - store_test_results:
                path: test_results
            - store_artifacts:
                path: test_results


workflows:
    version: 2
    dependencies:
        jobs:
            - build
            - test:
                requires:
                    - build
